### ISSUE TITLE
Doesn't work on Android (ARM64 architecture in general)

### ISSUE THREAD

**Issue by Klewerro** [henkelmax/opus4j#3]
Library version: 2.0.2
StackTrace:
```
...

Caused by: de.maxhenkel.opus4j.UnknownPlatformException: Could not find opus4j natives for platform linux-aarch64
                                                                                                    	at de.maxhenkel.opus4j.LibraryLoader.load(LibraryLoader.java:113)
                                                                                                    	at de.maxhenkel.opus4j.Opus.load(Opus.java:32)
                                                                                                    	at de.maxhenkel.opus4j.OpusEncoder.<init>(OpusEncoder.java:19)
                                                                                                    	at com.example.speakerpoc.MainActivity.encodeAudioUsingLibrary(MainActivity.kt:141)
                                                                                                    	at com.example.speakerpoc.MainActivity.encodeFileUsingOpus(MainActivity.kt:125)
                                                                                                    	at com.example.speakerpoc.MainActivity.setupButtons$lambda$3$lambda$1(MainActivity.kt:49)
                                                                                                    	at com.example.speakerpoc.MainActivity.$r8$lambda$-TsL4DalP-5eJBwDry_a-WqqtNo(Unknown Source:0)
                                                                                                    	at com.example.speakerpoc.MainActivity$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
                                                                                                    	at android.view.View.performClick(View.java:7506)
                                                                                                    	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1211)
                                                                                                    	at android.view.View.performClickInternal(View.java:7483)
                                                                                                    	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
                                                                                                    	at android.view.View$PerformClick.run(View.java:29335)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7898)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
```

**Comment by henkelmax** [comment]
Android is not supported.
